  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: Quarkus Petclinic REST AWS Lambda - Users API (Native)
  Globals:
    Api:
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - "*/*"

  Parameters:
    dbUsername:
      Type: String
      Description: DB username
    dbPassword:
      Type: String
      Description: DB password
    dbHost:
      Type: String
      Description: DB host
    dbPort:
      Type: String
      Description: DB port
    dbDatabase:
      Type: String
      Description: DB database

  Resources:
    UsersNative:
      Type: AWS::Serverless::Function
      Properties:
        Handler: not.used.in.provided.runtimei
        Runtime: provided
        CodeUri: target/function.zip
        MemorySize: 512
        Policies: AWSLambdaBasicExecutionRole
        Timeout: 15
        Environment:
          Variables:
            DISABLE_SIGNAL_HANDLERS: true
            DB_USERNAME: !Ref dbUsername
            DB_PASSWORD: !Ref dbPassword
            DB_HOST: !Ref dbHost
            DB_PORT: !Ref dbPort
            DB_DATABASE: !Ref dbDatabase
        Events:
          HttpApiEvent:
            Type: HttpApi

  Outputs:
    UserNativeApi:
      Description: URL for application
      Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/'
      Export:
        Name: QuarkusPetclinicRestUserNativeApi
