name: DevelopmentCI

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

env:
  SHORT_SHA_12: $(git rev-parse --short=12 ${{ github.sha }})

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      owners: ${{ steps.filter.outputs.owners }}
      pets: ${{ steps.filter.outputs.pets }}
      pettypes: ${{ steps.filter.outputs.pettypes }}
      specialties: ${{ steps.filter.outputs.specialties }}
      users: ${{ steps.filter.outputs.users }}
      vets: ${{ steps.filter.outputs.vets }}
      visits: ${{ steps.filter.outputs.visits }}
    steps:
      # Clone git project
      - name: 'Clone Git Project'
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            owners:
              - 'owners/**'
            pets:
              - 'pets/**'
            pettypes:
              - 'pettypes/**'
            specialties:
              - 'specialties/**'
            users:
              - 'users/**'
            vets:
              - 'vets/**'
            visits:
              - 'visits/**'

  # Job to build and deploy maven submodule 'owners'
  build-submodule-owners:
    needs: changes
    if: ${{ needs.changes.outputs.owners == 'true' }}
    runs-on: ubuntu-latest
    steps:
      # Set up JDK 11
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Build and test the application
      - name: 'Build & Test'
        run: mvn clean package

  # ------------------------------------------------------------------------- #

  # Job to build and deploy maven submodule 'pets'
  build-submodule-pets:
    needs: changes
    if: ${{ needs.changes.outputs.pets == 'true' }}
    runs-on: ubuntu-latest
    steps:
      # Set up JDK 11
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Build and test the application
      - name: 'Build & Test'
        run: mvn clean package

  # ------------------------------------------------------------------------- #

  # Job to build and deploy maven submodule 'pettypes'
  build-submodule-pettypes:
    needs: changes
    if: ${{ needs.changes.outputs.pettypes == 'true' }}
    runs-on: ubuntu-latest
    steps:
      # Set up JDK 11
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Build and test the application
      - name: 'Build & Test'
        run: mvn clean package
  # ------------------------------------------------------------------------- #

  # Job to build and deploy maven submodule 'specialties'
  build-submodule-specialties:
    needs: changes
    if: ${{ needs.changes.outputs.specialties == 'true' }}
    runs-on: ubuntu-latest
    steps:
      # Set up JDK 11
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Build and test the application
      - name: 'Build & Test'
        run: mvn clean package

  # ------------------------------------------------------------------------- #

  # Job to build and deploy maven submodule 'users'
  build-submodule-users:
    needs: changes
    if: ${{ needs.changes.outputs.users == 'true' }}
    runs-on: ubuntu-latest
    steps:
      # Set up JDK 11
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Build and test the application
      - name: 'Build & Test'
        run: mvn clean package

  # ------------------------------------------------------------------------- #


  # Job to build and deploy maven submodule 'vets'
  build-submodule-vets:
    needs: changes
    if: ${{ needs.changes.outputs.vets == 'true' }}
    runs-on: ubuntu-latest
    steps:
      # Set up JDK 11
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Build and test the application
      - name: 'Build & Test'
        run: mvn clean package

  # ------------------------------------------------------------------------- #

  # Job to build and deploy maven submodule 'visits'
  build-submodule-visits:
    needs: changes
    if: ${{ needs.changes.outputs.visits == 'true' }}
    runs-on: ubuntu-latest
    steps:
      # Set up JDK 11
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Build and test the application
      - name: 'Build & Test'
        run: mvn clean package