name: Pull Requests

on:
  pull_request:
    branches: [ '**' ] # matches every branch
  workflow_dispatch:

jobs:
  jvm-build-job:
    runs-on: ubuntu-latest
    steps:
      # Clone git project
      - uses: actions/checkout@v2

      # Set up JDK 11
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Build and test the application
      - name: 'Build & Test'
        run: mvn clean package

  native-image-build-job:
    runs-on: ubuntu-latest
    steps:
      # Clone git project
      - uses: actions/checkout@v2

      # Set up GraalVM 20.3.1 with Java 11
      - name: 'Setup GraalVM Environment'
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: '20.3.1.java11'

      # Install GraalVM native-image plugin
      - name: 'Install GraalVM Native Image Plugin'
        run: |
          gu install native-image

      # Build and test the application
      - name: 'Build & Test Native Image'
        run: mvn package -Pnative
